services:
  aq2_42h:
    container_name: aq2_42h
    image: aqtiongame/server:latest
      # https://github.com/actionquake/distrib/tree/main/server#step-by-step
      # https://github.com/actionquake/serverconfigs/blob/main/docker/docker-compose.yaml
    ports:
      - "27910:27910/udp"
      - "27910:27910/tcp"
    environment:
      PORT: 27910
      TZ: Etc/UTC
      RCON_PASSWORD: ${RCON_PASSWORD:-pleaseupdateme}  # https://github.com/actionquake/serverconfigs/blob/f09f9baed0fada3649409f613d83c4185cb6763f/docker/aq2-entrypoint.sh#L27
    stdin_open: true
    tty: true
    restart: unless-stopped
    env_file:
      - ./base.env
      #- ./teamplay.env
      - ./deathmatch.env
    volumes:  # mounts to allow access and persist files on host, you will need to set appropriate permissions
      - ./teamplay.motd:/aq2server/action/motd.txt:ro
      - maps:/aq2server/action/maps
      - logs:/aq2server/action/logs
      - demos:/aq2server/action/demos
      - players:/aq2server/action/players

volumes:
  maps:
  logs:
  demos:
  players:
