services:
  aq2_42h:
    container_name: aq2_42h
    image: aqtiongame/server:latest
    ports:  # ports to map to host, cannot be in use and must correspond to same value as PORT variable in tp1.env
      - "27910:27910/udp"
      - "27910:27910/tcp"
    stdin_open: true
    tty: true
    restart: unless-stopped
    env_file:  # set server parameters in env_file
      - ./42h.env
    environment:  # set your local timezone
      - TZ=Etc/UTC
    volumes:  # mounts to allow access and persist files on host, you will need to set appropriate permissions
      - ./42h.motd:/aq2server/action/motd.txt:ro
      - maps:/aq2server/action/maps
      - logs:/aq2server/action/logs
      - demos:/aq2server/action/demos

volumes:
  maps:
  logs:
  demos:
